#if !canImport(ObjectiveC)
import XCTest

extension GCounterTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__GCounterTests = [
        ("testExample", testExample),
        ("testIncrementCounter", testIncrementCounter),
        ("testMakeIncrementCounterOperation", testMakeIncrementCounterOperation),
    ]
}

extension PNCounterTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PNCounterTests = [
        ("testDecrementCounter", testDecrementCounter),
        ("testExample", testExample),
        ("testIncrementCounter", testIncrementCounter),
        ("testMakeDecrementCounterOperation", testMakeDecrementCounterOperation),
        ("testMakeIncrementCounterOperation", testMakeIncrementCounterOperation),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(GCounterTests.__allTests__GCounterTests),
        testCase(PNCounterTests.__allTests__PNCounterTests),
    ]
}
#endif
