#if !canImport(ObjectiveC)
import XCTest

extension GSetTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__GSetTests = [
        ("testExample", testExample),
        ("testLessThan", testLessThan),
        ("testLessThanEqual", testLessThanEqual),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(GSetTests.__allTests__GSetTests),
    ]
}
#endif
