#if !canImport(ObjectiveC)
import XCTest

extension GSetTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__GSetTests = [
        ("testExample", testExample),
        ("testLessThan", testLessThan),
        ("testLessThanEqual", testLessThanEqual),
    ]
}

extension TwoPhaseSetTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TwoPhaseSetTests = [
        ("testExample", testExample),
        ("testLessThan", testLessThan),
        ("testLessThanEqual", testLessThanEqual),
        ("testLessThanEqualWithRemovedElements", testLessThanEqualWithRemovedElements),
        ("testLessThanWithRemovedElements", testLessThanWithRemovedElements),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(GSetTests.__allTests__GSetTests),
        testCase(TwoPhaseSetTests.__allTests__TwoPhaseSetTests),
    ]
}
#endif
