#if !canImport(ObjectiveC)
import XCTest

extension ActorDateTimestampTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ActorDateTimestampTests = [
        ("testExample", testExample),
    ]
}

extension ActorLogicalClockTimestampTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ActorLogicalClockTimestampTests = [
        ("testExample", testExample),
    ]
}

extension LWWRegisterTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__LWWRegisterTests = [
        ("testExample", testExample),
        ("testMergeThrowsErrorIfNotEqualValueForSameTimestamp", testMergeThrowsErrorIfNotEqualValueForSameTimestamp),
        ("testUpdateDifferentValueAndDifferentTimestamp", testUpdateDifferentValueAndDifferentTimestamp),
        ("testUpdateSameValueAndSameTimestamp", testUpdateSameValueAndSameTimestamp),
        ("testUpdateThrowsErrorIfDifferentValueAndSameTimestamp", testUpdateThrowsErrorIfDifferentValueAndSameTimestamp),
        ("testUpdateWithOldTimestamp", testUpdateWithOldTimestamp),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ActorDateTimestampTests.__allTests__ActorDateTimestampTests),
        testCase(ActorLogicalClockTimestampTests.__allTests__ActorLogicalClockTimestampTests),
        testCase(LWWRegisterTests.__allTests__LWWRegisterTests),
    ]
}
#endif
